SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIES](
	[CAT_ID] [int] NOT NULL,
	[CAT_NAME] [varchar](200) NOT NULL,
	[CAT_IMAGE] [varchar](500) NULL,
	[CAT_ACTIVE] [smallint] NOT NULL,
	[PROD_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIES] ADD PRIMARY KEY CLUSTERED 
(
	[CAT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIES]  WITH CHECK ADD  CONSTRAINT [FK_CAT] FOREIGN KEY([PROD_ID])
REFERENCES [dbo].[PRODUCT] ([PROD_ID])
GO
ALTER TABLE [dbo].[CATEGORIES] CHECK CONSTRAINT [FK_CAT]
GO
