SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[ORD_ID] [int] NOT NULL,
	[PROD_ID] [int] NULL,
	[ORD_QTY] [int] NOT NULL,
	[DATE] [date] NULL,
	[ORD_AMT] [float] NOT NULL,
	[SHIP_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS] ADD PRIMARY KEY CLUSTERED 
(
	[ORD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_PROD_ID] FOREIGN KEY([PROD_ID])
REFERENCES [dbo].[PRODUCT] ([PROD_ID])
GO
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_PROD_ID]
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_SHIP_ID] FOREIGN KEY([SHIP_ID])
REFERENCES [dbo].[SHIPPING] ([SHIP_ID])
GO
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_SHIP_ID]
GO
