SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT](
	[PROD_ID] [int] NOT NULL,
	[PROD_NAME] [varchar](200) NOT NULL,
	[PROD_IMAGE] [varchar](500) NULL,
	[PROD_ACTIVE] [smallint] NOT NULL,
	[PROD_PRICE] [float] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCT] ADD PRIMARY KEY CLUSTERED 
(
	[PROD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
