SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SHIPPING](
	[SHIP_ID] [int] NOT NULL,
	[SHIP_METHOD] [varchar](20) NULL,
	[CHARGE] [float] NULL,
	[DATE] [date] NULL,
	[ACC_ID] [int] NULL,
	[ADD_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIPPING] ADD PRIMARY KEY CLUSTERED 
(
	[SHIP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIPPING]  WITH CHECK ADD  CONSTRAINT [FK_SHIPPING_ACC_ID] FOREIGN KEY([ACC_ID])
REFERENCES [dbo].[USERAC] ([ACC_ID])
GO
ALTER TABLE [dbo].[SHIPPING] CHECK CONSTRAINT [FK_SHIPPING_ACC_ID]
GO
ALTER TABLE [dbo].[SHIPPING]  WITH CHECK ADD  CONSTRAINT [FK_SHIPPING_ADD_ID] FOREIGN KEY([ADD_ID])
REFERENCES [dbo].[ADDRESS] ([ADD_ID])
GO
ALTER TABLE [dbo].[SHIPPING] CHECK CONSTRAINT [FK_SHIPPING_ADD_ID]
GO
