SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERAC](
	[ACC_ID] [int] NOT NULL,
	[ID] [varchar](200) NOT NULL,
	[PASWD] [char](8) NOT NULL,
	[TIMESTMP] [time](7) NULL,
	[PHN] [int] NOT NULL,
	[TRANS_AMNT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERAC] ADD PRIMARY KEY CLUSTERED 
(
	[ACC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
